lower_bound: [150, 100, 100]
upper_bound: [151, 150, 150]
lower_bound_car: [120, 0, 0]
upper_bound_car: [130, 255, 255]
canny_lower: 50
canny_upper: 150
fov: 0.55
hough_rho: 6
hough_threshold: 30
hough_min_line_length: 20
hough_max_line_gap: 25
angle_lower_bound: 30
angle_upper_bound: 60
deviation_threshold: 1
create_visualisation: False