# this is the only docker-compose 2.x version supporting NVIDIA GPUs
version: '2.3'

services:
  carla-simulator:
    image: carla-sim
    runtime: nvidia
    security_opt:
      - seccomp:unconfined
    environment:
      SDL_VIDEODRIVER: x11
      SDL_HINT_CUDA_DEVICE: 0
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    expose:
      - 2000
      - 2001
      - 2002
    networks:
      - carla

  roscore:
    image: ros:noetic
    command: roscore
    expose:
      - 11311
    networks:
      - ros

  carla-ros-bridge:
    image: carla-ros-bridge
    environment:
      CARLA_SIM_HOST: carla-simulator
      CARLA_SIM_WAIT_SECS: 20
      ROS_MASTER_URI: http://roscore:11311
      ROS_HOSTNAME: carla-ros-bridge
    networks:
      - carla
      - ros

networks:
  carla:
  ros:
