version: '2'

services:
  carla-sim:
    image: carla-sim
    build:
      context: ./carla_sim
      args:
        - CARLA_VERSION=0.9.10.1

  carla-ros-bridge-base:
    image: carla-ros-bridge-base
    build:
      context: https://github.com/carla-simulator/ros-bridge.git#0.9.10.1
      dockerfile: docker/Dockerfile
      args:
        - ROS_VERSION=noetic
        - CARLA_VERSION=0.9.10.1

  carla-ros-bridge:
    image: carla-ros-bridge
    build:
      context: ./carla_ros_bridge_ui
      args:
        - ROS_BRIDGE_BASE_IMG=carla-ros-bridge-base
    depends_on:
      - carla-ros-bridge-base

  test_subscriber_camera:
    image: test_subscriber_camera
    build:
      context: ./test_subscriber_camera

  vehicle_controller:
    image: vehicle_controller
    build:
      context: ./vehicle_controller
