version: '2'

services:
  carla-sim:
    image: carla-sim
    build:
      context: ./carla_sim
      args:
        - CARLA_VERSION=0.9.10.1

  carla-ros-bridge:
    image: carla-ros-bridge
    build:
      context: ./carla_ros_bridge
      args:
        - CARLA_VERSION=0.9.10.1

  launch-service:
    image: launch_service
    build:
      context: ./launch_service
      args:
        - CARLA_VERSION=0.9.10.1
