version: '2.3'

services:
  roscore:
    image: ros:noetic
    command: roscore
    expose:
      - 11311
    networks:
      - ros

  carla-sim-mock:
    image: ros:noetic
    command: /integration-tests-startup.sh
    volumes:
      - ./integration-tests-startup.sh:/integration-tests-startup.sh
      - ./recordings:/app/recordings
    environment:
      ROS_MASTER_URI: http://roscore:11311
      ROS_HOSTNAME: carla-sim-mock
    networks:
      - ros

  vehicle_control:
    image: vehicle_control
    environment:
      ROS_MASTER_URI: http://roscore:11311
      ROS_HOSTNAME: vehicle_control
    networks:
      - ros

  perception:
    image: perception
    environment:
      ROS_MASTER_URI: http://roscore:11311
      ROS_HOSTNAME: perception
    networks:
      - ros

networks:
  ros:
