# this is the only docker-compose 2.x version supporting NVIDIA GPUs
version: '2.3'

services:
  carla-simulator:
    image: carla-sim
    runtime: nvidia
    security_opt:
      - seccomp:unconfined
    environment:
      SDL_VIDEODRIVER: offscreen
      SDL_HINT_CUDA_DEVICE: 0
    expose:
      - 2000
      - 2001
      - 2002
    networks:
      - carla
    command: ["-carla-server"]

  roscore:
    image: ros:noetic
    command: roscore
    expose:
      - 11311
    networks:
      - ros

  carla-ros-bridge:
    image: carla-ros-bridge
    runtime: nvidia
    security_opt:
      - seccomp:unconfined
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      # - ./ego_vehicle_sensors.json:/ego_vehicle_sensors.json
      - ./custom_rosbridge_startup.launch:/custom_rosbridge_startup.launch
    environment:
      SDL_VIDEODRIVER: x11
      SDL_HINT_CUDA_DEVICE: 0
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: 1
      ROS_MASTER_URI: http://roscore:11311
      ROS_HOSTNAME: carla-ros-bridge
      CARLA_SIM_HOST: carla-simulator
      CARLA_SIM_WAIT_SECS: 20
      CARLA_OPENSCENARIO_FILE: /opt/scenario_runner/srunner/examples/FollowLeadingVehicle.xosc
      SCENARIO_RUNNER_PATH: /opt/scenario_runner
      # EGO_VEHICLE_SENSORS: /ego_vehicle_sensors.json
    networks:
      - carla
      - ros
    command: ["/custom_rosbridge_startup.launch", "--wait"]

  # vehicle-controller:
  #   image: vehicle_controller
  #   environment:
  #     ROS_MASTER_URI: http://roscore:11311
  #     ROS_HOSTNAME: vehicle-controller
  #   networks:
  #     - ros

networks:
  carla:
  ros:
