competition:
  goal:
    position:
      x: 106.00283813476562
      y: -92.81285095214844
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.6091592
      w: 0.7930479
  start:
    position:
      x: -84.63275909423828
      y: -16.467145919799805
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.9999997
      w: 0.0007963

  traffic_rules: true
  ready_for_ego: false
  town_name: 'Town10HD'
  spawn_npc:
    n: 50 # orig: 50
    w: 50 # orig: 50
    s: 1 # seed